# Generated by Django 5.2.4 on 2025-07-14 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("memories", "0001_initial"),
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmemory",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memories",
                to="user.organization",
            ),
        ),
        migrations.AddField(
            model_name="teammemory",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memories",
                to="user.team",
            ),
        ),
        migrations.AddField(
            model_name="usermemory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmemory",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="memories_or_organiz_2545b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmemory",
            index=models.Index(
                fields=["organization", "status"], name="memories_or_organiz_69fd11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammemory",
            index=models.Index(
                fields=["team", "-created_at"], name="memories_te_team_id_04e5cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammemory",
            index=models.Index(
                fields=["team", "status"], name="memories_te_team_id_bba9cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermemory",
            index=models.Index(
                fields=["user", "-created_at"], name="memories_us_user_id_4b6320_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermemory",
            index=models.Index(
                fields=["user", "status"], name="memories_us_user_id_1c951a_idx"
            ),
        ),
    ]
