# Generated by Django 5.2.4 on 2025-07-14 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memories', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmemory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='user.organization'),
        ),
        migrations.AddField(
            model_name='teammemory',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='user.team'),
        ),
        migrations.AddField(
            model_name='usermemory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organizationmemory',
            index=models.Index(fields=['organization', '-created_at'], name='memories_or_organiz_2545b5_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmemory',
            index=models.Index(fields=['organization', 'processing_status'], name='memories_or_organiz_010f88_idx'),
        ),
        migrations.AddIndex(
            model_name='teammemory',
            index=models.Index(fields=['team', '-created_at'], name='memories_te_team_id_04e5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='teammemory',
            index=models.Index(fields=['team', 'processing_status'], name='memories_te_team_id_701c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='usermemory',
            index=models.Index(fields=['user', '-created_at'], name='memories_us_user_id_4b6320_idx'),
        ),
        migrations.AddIndex(
            model_name='usermemory',
            index=models.Index(fields=['user', 'processing_status'], name='memories_us_user_id_c32580_idx'),
        ),
    ]
