# Generated by Django 5.2.4 on 2025-07-14 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organizationmemory',
            name='memories_or_organiz_010f88_idx',
        ),
        migrations.RemoveIndex(
            model_name='teammemory',
            name='memories_te_team_id_701c0a_idx',
        ),
        migrations.RemoveIndex(
            model_name='usermemory',
            name='memories_us_user_id_c32580_idx',
        ),
        migrations.RenameField(
            model_name='organizationmemory',
            old_name='processing_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='teammemory',
            old_name='processing_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='usermemory',
            old_name='processing_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='organizationmemory',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='teammemory',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='usermemory',
            name='is_processed',
        ),
        migrations.AddIndex(
            model_name='organizationmemory',
            index=models.Index(fields=['organization', 'status'], name='memories_or_organiz_69fd11_idx'),
        ),
        migrations.AddIndex(
            model_name='teammemory',
            index=models.Index(fields=['team', 'status'], name='memories_te_team_id_bba9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='usermemory',
            index=models.Index(fields=['user', 'status'], name='memories_us_user_id_1c951a_idx'),
        ),
    ]
