# Generated by Django 5.2.4 on 2025-07-14 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['primary_key'], name='authenticat_primary_7474d5_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['secondary_key'], name='authenticat_seconda_7df287_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['user'], name='authenticat_user_id_bc7681_idx'),
        ),
    ]
